### ISSUE TITLE
Feature Request: manyOf can optionally return empty array instead of undefined

### ISSUE THREAD

**Issue by tinleym** [mswjs/data#199]
## Use Case
GraphQL schemas may require an array type, in which case returning undefined will throw an error. The current workaround is to explicitly extract all fields from an Entity and append an or fallback to all manyOf fields. It would be nice if this wasn't the case.

## API Change
Change the manyOf(entityName: string) declaration to manyOf(entityName: string, emptyArrayFallback?: boolean)

Happy to submit a PR if this fits the goals of the library!

**Comment by kettanaito** [comment]
Hey, @tinleym. Thanks for suggesting this!

I think this is a good idea. Listing methods should always return a list which may or may not be filled with entities that match the criteria. 

Sharing some of the similar APIs below for inspiration:

```js
document.querySelectorAll('#noop')
// NodeList []
```

```js
prisma.users.findMany({ ... })
// []
```

> [See Prisma docs on `findMany`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-2)

Since we model our public API to resemble Prisma, that's a big argument to migrate to the return type you're proposing. 

Please, go ahead and open a pull request with this change. I'd be glad to review and merge it. Thank you!
