### ISSUE TITLE
How to save a File in msw-data

### ISSUE THREAD

**Issue by akshymalvia** [mswjs/data#253]
Here's how I've defined the model definition for file type, not using File or Blob constructors as they're throwing errors.

Model definition
```javascript
import { uid } from "quasar";
import { primaryKey } from "@mswjs/data";

export default {
  id: primaryKey(uid),
  dateCreated: () => new Date(),
  dateUpdated: () => new Date(),
  content: Object,
};
```

The way I'm trying to create the model instance.
```javascript
import { db } from "../database";

const createdFile = db.file.create({content: File});
```

I'm getting this as `createdFile`, empty object as content instead of the File.

```javascript
{
  id: primaryKey(uid),
  dateCreated: () => new Date(),
  dateUpdated: () => new Date(),
  content: {}
}
```

I don't know what I'm doing wrong here.

Using  `@mswjs/data^0.10.2`

**Comment by kettanaito** [comment]
Hey, @akshymalvia.

What error do you get when using the `File` instance in the model definition?

```js
export default {
  id: primaryKey(uid),
  dateCreated: () => new Date(),
  dateUpdated: () => new Date(),
  content: () => new File([], 'default'),
};
```

**Comment by akshymalvia** [comment]
Hi, @kettanaito thanks for the quick response.

This is the error that I'm getting

![Screenshot 2022-11-24 at 16 35 54](https://user-images.githubusercontent.com/30196863/203769372-7eb81e67-119a-411c-bdf7-4061f2a707e5.png)

**Comment by kettanaito** [comment]
Here's an example of using `File` as a model value:

```ts
import { factory, primaryKey } from "@mswjs/data";

const db = factory({
  file: {
    id: primaryKey(() => Math.random().toString(32).slice(2)),
    content: () => new File([], "")
  }
});

const file = db.file.create({
  content: new File(["hello"], "filename.txt")
});

console.log(file);
```

- [View on CodeSandbox](https://codesandbox.io/s/mswjs-data-file-instance-0t47ti)

Note that this won't be compatible with TypeScript because `File` is not assignable to the model value type that the library expects:

https://github.com/mswjs/data/blob/efb17476bc8fedb759b4f0977bc2b96df6ebc0ff/src/glossary.ts#L21-L22

We seem to be explicit about the supported types. Maybe this is a room for improvement in the future.

**Comment by akshymalvia** [comment]
> Here's an example of using `File` as a model value:
> 
> ```ts
> import { factory, primaryKey } from "@mswjs/data";
> 
> const db = factory({
>   file: {
>     id: primaryKey(() => Math.random().toString(32).slice(2)),
>     content: () => new File([], "")
>   }
> });
> 
> const file = db.file.create({
>   content: new File(["hello"], "filename.txt")
> });
> 
> console.log(file);
> ```
> 
> * [View on CodeSandbox](https://codesandbox.io/s/mswjs-data-file-instance-0t47ti)
> 
> Note that this won't be compatible with TypeScript because `File` is not assignable to the model value type that the library expects:
> 
> https://github.com/mswjs/data/blob/efb17476bc8fedb759b4f0977bc2b96df6ebc0ff/src/glossary.ts#L21-L22
> 
> We seem to be explicit about the supported types. Maybe this is room for improvement in the future.

Hey @kettanaito, thanks for the Sandbox.

There's an issue with file creation, the created file does not have the contents of the file assigned to `content` key, instead, it has the contents of the initial model definition, I faced this issue locally and then checked out the Sandbox, and the behavior is the same.

**Comment by akshymalvia** [comment]
> Hey @kettanaito, thanks for the Sandbox.
> 
> There's an issue with file creation, the created file does not have the contents of the file assigned to `content` key, instead, it has the contents of the initial model definition, I faced this issue locally and then checked out the Sandbox, and the behavior is the same.

Why the created file doesn't have the assigned content?

**Comment by kettanaito** [comment]
Likely because we don't have support for custom classes as model value types, as I've said. I don't know at the moment what such support would imply, I haven't worked on Data in quite some time. 

Because `File` is not a primitive value, so this check fails:

https://github.com/mswjs/data/blob/efb17476bc8fedb759b4f0977bc2b96df6ebc0ff/src/model/createModel.ts#L87

https://github.com/mswjs/data/blob/efb17476bc8fedb759b4f0977bc2b96df6ebc0ff/src/utils/isModelValueType.ts#L12

Then, `createModel` uses the property definition function to populate the value:

https://github.com/mswjs/data/blob/efb17476bc8fedb759b4f0977bc2b96df6ebc0ff/src/model/createModel.ts#L98

And since that property definition is `() => new File([], '')` (the default value from the model definition), you always get that default value no matter which custom value you provide when creating a model.

**Comment by akshymalvia** [comment]
Hi @kettanaito, thanks for the answer.

I want to work on adding support for `File`. Would you think it through, should it be supported or not?

I can also help implement persistence if you guide me through it, like how it should be implemented.
